### ISSUE TITLE
Add Frontend, Bundler section

### ISSUE THREAD

**Issue by ryota-murakami** [Maximization/nodejs-toolbox-catalog#5]
Thanks for creating great project!
This is so helpful as a React dev like me though, I wonder is this project for backend specific stuff?

**Comment by koresar** [comment]
I'm not sure what is in the mind of the original author, but to me this looks like very much Node.js runtime specific. Meaning, this looks like not in-browser JS project.

**Comment by Maximization** [comment]
Thank you @ryota-murakami  🤗.

@koresar Is correct. The toolbox is specific to the Node.js ecosystem for now. There is some overlap with frontend and React (packages that can be used both in the browser and Node.js like axios), so you might still find it useful.

As for bundlers I think they do deserve a category because the bundling itself is done in the backend within the Node.js runtime (even though it serves mostly for frontend).

Feel free to open PR with the new category. Have a look at another category as example.

**Comment by Maximization** [comment]
Added Bundlers category: https://nodejstoolbox.com/categories/bundlers

**Comment by ryota-murakami** [comment]
@Maximization Thank you so much! 😄
